feat: update github token

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -14,6 +14,15 @@ jobs:
         node-version: ["18.x"]
 
     steps:
+      - name: "Check for GitHub Token"
+        run: |
+          if [ -z "${{ secrets.ACTION_TOKEN }}" ]; then
+            echo "GitHub token is missing"
+            exit 1
+          else
+            echo "GitHub token is present"
+          fi
+
       - name: Checkout PR
         uses: actions/checkout@v4
         with:
@@ -191,13 +200,13 @@ jobs:
           # GITHUB_TOKEN은 GitHub Actions 워크플로우에서 자동으로 생성되고 제공되는 암호화된 토큰
           # Actions secrets에 자동으로 포함되므로 사용자가 명시적으로 설정하지 않아도 됨
           # 워크플로우 실행 중 특정 작업을 수행하는 데 필요한 권한을 제공하는 등의 경우에 사용됨
-          github-token: ${{ secrets.GITHUB_TOKEN }}
+          github-token: ${{ secrets.ACTION_TOKEN }}
           script: |
             const fs = require('fs');
             # GitHub의 REST API와 상호 작용하기 위한 라이브러리
             # GitHub 레포지토리, 이슈, PR, 사용자 정보 등 다양한 데이터를 쉽게 조회하고 조작할 수 있음
             const { Octokit } = require('@octokit/rest');
-            const octokit = new Octokit({ auth: `${{ secrets.GITHUB_TOKEN }}` });
+            const octokit = new Octokit({ auth: `${{ secrets.ACTION_TOKEN }}` });
 
             # context 객체는 @actions/github 패키지에서 제공하는 것으로, 워크플로우 실행 중 현재 컨텍스트에 대한 정보를 담고 있음
             # repo를 통해 현재 레포지토리에 대한 정보를 가져올 수 있음
